Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-09, with the labels that each got.

#588 Feature/이미지 업로더 사진 받아오기 #587
  src/api/dto.ts
  src/components/Uploader/ImageUploader.tsx
Labels: Feature, P1

#589 Feature/스터디 페이지 구현 #428
  src/api/dto.ts
  src/api/studyApi.ts
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Accordion/StudyAccordionBody.tsx
  src/pages/Study/Accordion/StudyAccordionHeader.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/Study.tsx
Labels: Feature, Design, P1

#590 Feature/테이블 높이 줄이기 #130
  src/components/Table/StandardTable.tsx
Labels: Design

#586 Feature/도서, 도서관리 search section api 연결 #585
  src/api/dto.ts
  src/api/libraryApi.ts
  src/api/libraryManageApi.ts
  src/pages/Library/Library.tsx
  src/pages/Library/SearchSection/LibrarySearchSection.tsx
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
Labels: Feature, P2

#593 Feature/도서검색 사서 이름 받아오기 #592
  src/pages/Library/Library.tsx
Labels: Feature

#598 Feature/게시글 조회 세부 기능 추가 #526
  src/api/commentApi.ts
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Uploader/ImageUploader.tsx
  src/pages/board/BoardView/Card/CommentCard.tsx
  src/pages/board/BoardView/Card/CommentCardHeader.tsx
  src/pages/board/BoardView/Card/ReplyCard.tsx
  src/pages/board/BoardView/Section/BannerSection.tsx
  src/pages/board/BoardWrite/BoardWrite.tsx
  src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
Labels: Feature, P1

#599 Feature/익명 게시판 임시저장 안 되도록 처리 및 안내 문구 띄우기 #595
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Section/CommentSection.tsx
  src/pages/board/BoardWrite/BoardWrite.tsx
Labels: Feature, Design

#600 Feature/비밀글 url로 접근 시 처리 #578
  src/App.tsx
  src/api/postApi.ts
  src/pages/board/BoardView/BoardView.tsx
Labels: Feature

#604 feat : 승인요청 페이지 대출,반납 정보만 받아와지도록
  src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
Labels: Feature

#602 feat : 도서페이지 썸네일 적용
  src/pages/Library/Card/BookCard.tsx
Labels: Feature

#611 Feature/게시글 파일 수정 #597
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Uploader/FileUploadList.tsx
  src/components/Uploader/FileUploader.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
  src/pages/board/BoardWrite/BoardWrite.tsx
Labels: Feature, P1

#609 Feature/게시판 그리드뷰 다듬기
  src/components/Card/FixedPostingCard.tsx
  src/components/Card/PostingCard.interface.ts
  src/components/Card/PostingCard.tsx
  src/components/Table/GridTable.tsx
  src/pages/board/BoardList/BoardList.tsx
Labels: Feature, Design, P1

#613 Feature/최신글 n 표시해주기 #612
  src/components/Card/FixedPostingCard.tsx
  src/components/Card/PostingCard.interface.ts
  src/components/Card/PostingCard.tsx
  src/pages/board/BoardList/BoardList.tsx
Labels: Feature, Design, P2

#614 feat : 프로필 페이지 레이아웃 구현
  src/pages/Profile/Profile.tsx
  src/pages/Profile/Tab/AttendanceTab.tsx
  src/pages/Profile/Tab/BoardTab.tsx
  src/pages/Profile/Tab/BookTab.tsx
  src/pages/Profile/Tab/PointTab.tsx
  src/router/useMainRouter.tsx
Labels: Design

#618 feature/직책관리 페이지 백엔드 API 변수명 변경 적용
  src/api/dto.ts
  src/api/dutyManageApi.ts
  src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
Labels: Refactor

#621 Feature/ServerImg null 일때 api 호출로 인한 콘솔 에러 제거 #509
  src/components/Image/ServerImg.tsx
Labels: Feature

#622 Feature/삭제된 댓글 아래 여백 없도록 처리 #608
  src/pages/board/BoardView/Card/CommentCard.tsx
Labels: Feature

#630 Feature/로그인 회원가입 공통 컴포넌트 빼주기 #623
  src/components/Input/BackgroundInput.tsx
  src/components/Input/EmailAuthInput.tsx
  src/components/Input/StandardInput.tsx
  src/components/Input/TimerInput.tsx
  src/components/Typography/TextTimer.tsx
  src/pages/SignUp/Section/SignUpFirstInputSection.tsx
  src/pages/SignUp/Section/SignUpSecondInputSection.tsx
  src/pages/SignUp/Section/SignUpThirdInputSection.tsx
  src/pages/login/Login.tsx
  src/pages/login/Search/SearchID.tsx
  src/pages/login/Search/SearchPWFirstStep.tsx
  src/pages/login/Search/SearchPWSecondStep.tsx
Labels: Feature, Design, P1

#628 feat : 레이아웃 full container로 수정
  src/components/Layout/Container/FullContainer.tsx
  src/pages/Profile/Profile.tsx
  src/router/useMainRouter.tsx
Labels: Design

#635 feat : StandardDatePicker 배경색 확장 및 UI 개선
  src/components/DatePicker/StandardDatePicker.tsx
  src/pages/SignUp/Section/SignUpSecondInputSection.tsx
Labels: Feature, Design, P1

#634 Feature/헤더 메뉴에 프로필 경로 이동 기능 구현 #632
  src/components/Layout/Header/Menu/AccountMenu.tsx
Labels: Feature

#639 Feature/회원가입 프로필 정보 단계 기능 구현 #296
  src/components/DatePicker/StandardDatePicker.tsx
  src/constants/errorMsg.ts
  src/pages/SignUp/Section/SignUpSecondInputSection.tsx
  src/pages/SignUp/SignUp.recoil.ts
  src/pages/SignUp/SignUp.tsx
  src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
Labels: Feature, P1

#640 Feature/회원가입 이메일 인증 단계 기능 구현 #297
  src/api/dto.ts
  src/api/signUpApi.ts
  src/components/Input/EmailAuthInput.tsx
  src/components/Input/StandardInput.tsx
  src/components/Input/TimerInput.tsx
  src/pages/SignUp/Section/SignUpSecondInputSection.tsx
  src/pages/SignUp/Section/SignUpThirdInputSection.tsx
  src/pages/login/Search/SearchID.tsx
  src/pages/login/Search/SearchPWFirstStep.tsx
  src/utils/validateEmail.ts
Labels: Feature, Design, P3

#643 Feature/내 프로필 출석부 탭 구현 #554
  package-lock.json
  package.json
  src/api/dto.ts
  src/pages/Profile/Tab/AttendanceTab.tsx
Labels: Feature, Design, P1

#645 Feature/게임 포인트 부족할 때 관련해서 처리 #644
  src/pages/Game/Baseball/api/baseballApi.ts
Labels: Feature

#646 fix : 메뉴를 통한 경로 이동 시에 에러 발생하지 않도록 메뉴창 닫아주도록 처리
  src/components/Layout/Header/Menu/AccountMenu.tsx
Labels: Bug

#649 Feature/인풋 자동 완성 시 배경색 안 들어가도록 처리 #648
  src/constants/muiTheme.ts
Labels: Feature, Design

#641 Feature/프로필 포인트탭 #617
  src/api/dto.ts
  src/api/pointApi.ts
  src/pages/Profile/Tab/PointTab.tsx
Labels: Feature

#650 feat : Radio Button 코드 위치 이동
  src/components/Input/RadioButton.tsx
  src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
Labels: Refactor

#656 Feature/회원가입 남은 작업 처리 - 중복 체크 관련
  src/api/signUpApi.ts
  src/components/Input/EmailAuthInput.tsx
  src/pages/SignUp/Section/SignUpFirstInputSection.tsx
  src/pages/SignUp/Section/SignUpSecondInputSection.tsx
  src/pages/SignUp/Section/SignUpThirdInputSection.tsx
Labels: Feature

#657 Feature/내 프로필 출석부 탭 구현 - 반응형 #554
  src/components/Layout/Sidebar/Sidebar.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Profile/Tab/AttendanceTab.tsx
Labels: Design, P1

#651 Feature/AutoComplete 컴포넌트 개선 #615
  src/components/Input/AutoComplete.tsx
  src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
  src/pages/admin/MeritManage/Modal/AddMeritModal.tsx
Labels: Refactor

#662 Feature/상벌점 페이지 회원상벌점내역 모달 #653
  src/api/meritApi.ts
  src/pages/admin/MeritManage/Modal/MemberMeritModal.tsx
  src/pages/admin/MeritManage/Tab/UserMeritTab.tsx
Labels: Feature

#664 fest : 프로필 섹션 ui 구성 및 회원정보 연결
  src/api/dto.ts
  src/api/memberApi.ts
  src/pages/Profile/Profile.tsx
  src/pages/Profile/Section/ProfileSection.tsx
Labels: Feature, Design

#665 Feature/page param key 받아서 처리 가능하도록 확장 #658
  src/components/Pagination/StandardTablePagination.interface.ts
  src/components/Pagination/StandardTablePagination.tsx
  src/hooks/usePagination.ts
Labels: Feature, P1

#655 Feature/프로필 작성글탭 #642
  src/api/dto.ts
  src/api/postApi.ts
  src/pages/Profile/Tab/BoardTab.tsx
  src/pages/Profile/Tab/BoardTable/MyBoardTable.tsx
  src/pages/Profile/Tab/BoardTable/TempBoardTable.tsx
Labels: Feature

#667 Feature/족보 게시판 관련 처리 #579
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Viewer/FileViewer.tsx
  src/pages/board/BoardView/Modal/WarningDeductPointModal.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
Labels: Feature, Design

#668 Feature/내 프로필 출석부 탭 구현 - 기능 구현 #554
  src/api/attendanceApi.ts
  src/api/dto.ts
  src/pages/Profile/Profile.tsx
  src/pages/Profile/Tab/AttendanceTab.tsx
  src/pages/Profile/Tab/AttendanceTab/AttendanceTab.tsx
  src/pages/Profile/Tab/AttendanceTab/Card/AttendRankPointCard.tsx
  src/pages/Profile/Tab/AttendanceTab/Card/ContinuousDayPointCard.tsx
  src/pages/Profile/Tab/AttendanceTab/Card/TodayAttendPointCard.tsx
  src/pages/Profile/Tab/AttendanceTab/Section/AttendanceChartSection.tsx
  src/pages/Profile/Tab/AttendanceTab/Section/AttendanceGuideSection.tsx
  src/pages/Profile/Tab/AttendanceTab/Section/AttendanceInfoSection.tsx
Labels: Feature, Refactor, Design

#675 Feature/회원가입 인증 메일 안내 모달 기능 구현 #298
  src/components/Typography/TextTimer.tsx
  src/pages/SignUp/Section/SignUpThirdInputSection.tsx
  src/pages/login/Search/SearchID.tsx
  src/pages/login/Search/SearchPWFirstStep.tsx
Labels: Feature

#677 Feature/프로필 수정 모달 #676
  src/api/dto.ts
  src/api/dutyManageApi.ts
  src/api/memberApi.ts
  src/components/Modal/ActionModal.tsx
  src/components/Uploader/ProfileImageUploader.tsx
  src/mocks/UtilApi.ts
  src/pages/Profile/Modal/EditProfileModal.tsx
  src/pages/Profile/Section/ProfileSection.tsx
Labels: Feature, Design

#681 Feature/프로필 작성글 포인트 usePagination #680
  src/pages/Profile/Profile.tsx
  src/pages/Profile/Tab/BoardTab/BoardTab.tsx
  src/pages/Profile/Tab/BoardTab/Table/MyBoardTable.tsx
  src/pages/Profile/Tab/BoardTab/Table/TempBoardTable.tsx
  src/pages/Profile/Tab/PointTab/PointTab.tsx
Labels: Feature

#692 Feature/계정 정보 수정 모달 #679
  src/api/memberApi.ts
  src/components/Modal/ConfirmModal.tsx
  src/pages/Profile/Modal/EditAccountModal.tsx
  src/pages/Profile/Section/ProfileSection.tsx
Labels: Feature, Design, P1

#697 Feature/스터디 검색 필터 적용 #428
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/Study.tsx
Labels: Feature, Design, P1

#701 Feature/헤더 사이드바 반응형 #700
  src/components/Layout/Header/Header.tsx
  src/components/Layout/MainLayout.tsx
  src/components/Layout/Sidebar/Sidebar.tsx
  src/constants/keeperTheme.ts
Labels: Feature, Design, P1

#704 feat : 헤더 높이에 따른 레이아웃 반응형 적용
  src/components/Layout/Container/FitContainer.tsx
  src/components/Layout/Container/FullContainer.tsx
Labels: Feature, Design, P1

#695 feat : 세미나 추가, 삭제 기능 구현
  src/api/dto.ts
  src/api/seminarApi.ts
  src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
  src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Feature

#698 Feature/계정 정보 수정 모달 - 탈퇴하기 #679
  src/api/memberApi.ts
  src/hooks/useGetApiError.ts
  src/pages/Profile/Modal/EditAccountModal.tsx
Labels: Feature

#708 Feature/로그인 반응형 적용 #705
  src/components/Layout/Container/FullContainer.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/MainLayout.tsx
  src/pages/login/Login.tsx
  src/pages/login/Search/SearchID.tsx
  src/pages/login/Search/SearchPW.tsx
  src/pages/login/Search/SearchPWFirstStep.tsx
  src/pages/login/Search/SearchPWSecondStep.tsx
  src/pages/login/Search/SearchPWThirdStep.tsx
  src/pages/login/SearchAccount.tsx
Labels: Feature, Design, P1

#691 design : 세미나 출석 반응형 적용
  src/pages/senimarAttend/SenimarAttend.tsx
  src/router/useMainRouter.tsx
Labels: Design

#688 feat : 스터디원, 스터디장 관리
  src/api/dto.ts
  src/api/logInApi.ts
  src/components/Input/AutoComplete.tsx
  src/pages/Study/Modal/StudyModal.tsx
Labels: Feature

#714 refector : AutoComplete z index 제거
  src/components/Input/AutoComplete.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
  src/pages/admin/MeritManage/Modal/AddMeritModal.tsx
Labels: Refactor, P1

#689 Feature/포인트선물하기 #682
  src/api/pointApi.ts
  src/pages/Profile/Modal/SendPointModal.tsx
Labels: Feature

#716 Feature/세미나 전부 조회 기능 #382
  src/api/dto.ts
  src/api/seminarApi.ts
  src/pages/admin/SeminarManage/SeminarManage.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
Labels: Feature, P1

#707 refactor : 도서검색 반응형 및 invalidateQueries문 추가
  src/api/libraryApi.ts
  src/pages/Library/Library.tsx
  src/pages/Library/Status/BorrowStatus.tsx
Labels: Feature, Design

#720 feat : SearchSection 컴포넌트 반응형 처리
  src/components/Input/SearchInput.tsx
  src/components/Section/SearchSection.tsx
Labels: Feature, Design, P1

#722 feat : 테이블 셀 선택 기능 확장
  src/components/Table/StandardTable.interface.ts
  src/components/Table/StandardTable.tsx
Labels: Feature, P1

#724 Feature/세미나 관리 세미나 cell 클릭 시 해당 출석 정보 다 받아오도록 처리 #723
  src/api/dto.ts
  src/api/seminarApi.ts
  src/pages/admin/SeminarManage/SeminarManage.tsx
Labels: Feature, P1

#738 feat : 총 출석일 반영
  src/api/dto.ts
  src/pages/Profile/Tab/AttendanceTab/Section/AttendanceInfoSection.tsx
Labels: Feature

#715 design : 랭킹페이지 반응형 처리
  src/pages/rank/Rank.tsx
Labels: Design

#727 Feature/게시글 목록 조회 반응형 #717
  src/components/Card/FixedPostingCard.tsx
  src/components/Card/PostingCard.tsx
  src/components/Table/GridTable.tsx
  src/components/Table/StandardTable.interface.ts
  src/components/Table/StandardTable.tsx
  src/pages/board/BoardList/BoardList.tsx
Labels: Feature, Design, P1

#733 Feature/회원가입 반응형 #732
  src/components/Input/TimerInput.tsx
  src/components/Modal/MailAuthenticationModal.tsx
  src/pages/SignUp/SignUp.tsx
Labels: Feature, Design

#736 Feature/게시글 작성 페이지 반응형 #734
  src/components/Editor/StandardEditor.tsx
  src/pages/board/BoardWrite/BoardWrite.tsx
  src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
Labels: Feature, Design

#678 refactor : 상벌점 페이지 개선
  src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
  src/pages/admin/MeritManage/Tab/MeritTypeTab.tsx
Labels: Refactor

#718 Feature/활동인원 관리 페이지 구현 #702
  src/api/dto.ts
  src/api/memberApi.ts
  src/pages/admin/ActiveMemberManage/ActiveMemberManage.tsx
  src/pages/admin/ActiveMemberManage/Button/ChangeMemberTypeButton.tsx
  src/pages/admin/ActiveMemberManage/Card/MemberCard.tsx
  src/pages/admin/ActiveMemberManage/Input/ChangeMemberTypeInput.tsx
  src/pages/admin/ActiveMemberManage/Section/MemberTypeSection.tsx
  src/pages/admin/ActiveMemberManage/Selector/SortSelector.tsx
  src/router/useMainRouter.tsx
Labels: Feature, Design

#739 Feature/프로필 섹션 뱃지 추가 #673
  src/api/dto.ts
  src/assets/profileBadge/profile_badge_state_graduate.gif
  src/assets/profileBadge/profile_badge_state_regular.gif
  src/assets/profileBadge/profile_badge_state_sleep.gif
  src/constants/badge.ts
  src/pages/Profile/Section/BadgeSection.tsx
  src/pages/Profile/Section/ProfileSection.tsx
Labels: Feature, Design, P1

#742 Feature/프로필 섹션 반응형 #740
  src/pages/Profile/Section/BadgeSection.tsx
  src/pages/Profile/Section/FollowList.tsx
  src/pages/Profile/Section/ProfileSection.tsx
Labels: Design, P2

#729 Feature/테이블 반응형 관련 처리 #726
  src/components/Pagination/StandardTablePagination.tsx
  src/components/Table/StandardTable.tsx
Labels: Feature, Design, P2

#709 Feature/스터디 수정 #699
  src/api/dto.ts
  src/api/studyApi.ts
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Accordion/StudyAccordionBody.tsx
  src/pages/Study/Accordion/StudyAccordionHeader.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/OldStudy.tsx
  src/pages/Study/Study.tsx
Labels: Feature

#731 Feature/게시글 조회 페이지 반응형 #730
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Card/CommentCard.tsx
  src/pages/board/BoardView/Card/CommentCardFooter.tsx
  src/pages/board/BoardView/Card/CommentCardHeader.tsx
  src/pages/board/BoardView/Card/CommentWriteCardAction.tsx
  src/pages/board/BoardView/Card/ReplyCard.tsx
  src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx
  src/pages/board/BoardView/Section/CommentSection.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
Labels: Feature, Design

#750 feat : 프로필 탭별 url 적용
  src/components/Tab/StandardTab.tsx
  src/pages/Profile/Profile.tsx
  src/router/useMainRouter.tsx
Labels: Feature, P1

#712 Feature/2022 이전 스터디 구현 #710
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Accordion/StudyAccordionHeader.tsx
  src/pages/Study/OldStudy.tsx
  src/pages/Study/Study.interface.ts
  src/pages/Study/Study.tsx
Labels: Feature

#743 Feature/도서관리 대출현황탭 api 연결 #671
  src/api/dto.ts
  src/api/libraryManageApi.ts
  src/pages/admin/LibraryManage/SearchSection/BorrowingStatusSearchSection.tsx
  src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
Labels: Feature, P1

#756 feat : 로그인 상태 유지 제거
  src/pages/login/Login.tsx
Labels: Feature

#746 fix : autocomplete 문제
  src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
  src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
Labels: Bug

#759 feat : 비밀번호 타입 적용
  src/pages/login/Login.tsx
  src/pages/login/Search/SearchPWSecondStep.tsx
Labels: Feature

#760 Feature/스터디 남은 기능 구현
  src/api/dto.ts
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Accordion/StudyAccordionBody.tsx
  src/pages/Study/Accordion/StudyAccordionHeader.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/Study.tsx
Labels: Feature, Design, P1

#764 Feature/스터디원 수정 #699
  src/api/dto.ts
  src/components/Input/AutoComplete.tsx
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Accordion/StudyAccordionBody.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/Study.tsx
Labels: Feature
