Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-05, with the labels that each got.

#288 Feature/스터디 정보 조회 기능 #154
  src/api/dto.ts
  src/mocks/StudyApi.ts
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/OldStudy.tsx
  src/pages/Study/Study.interface.ts
  src/pages/Study/Study.tsx
  src/pages/Study/share/StudyChip.tsx
  src/pages/Study/share/StudyInput.tsx
  src/pages/Study/share/StudySelect.tsx
Labels: Feature, Refactor, Design, P2

#311 Feature/confirm modal 제작 #290
  src/components/Modal/ConfirmModal.tsx
Labels: Feature, P1

#316 Feature/세미나 출석 카운트다운 구현 #308
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Countdown/Countdown.tsx
  src/pages/senimarAttend/Selector/SeminarSelector.tsx
Labels: Feature, P2

#366 Feature/Image 첨부 라이브러리 설치 #355
  package-lock.json
  package.json
Labels: Other, P1

#333 Feature/로그인페이지UI #146
  src/pages/login/Login.tsx
  src/router/useMainRouter.tsx
Labels: Feature, P1

#372 Feature/react hook form 설치 #371
  package-lock.json
  package.json
Labels: Feature, P1
