Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-06, with the labels that each got.

#374 Feature/EsLint 전개 연산자 관련 설정 off #373
  .eslintrc.js
Labels: Other, P2

#342 Feature/공통 tab 구현 #341
  src/components/Tab/StandardTab.tsx
Labels: Feature, P1

#344 Feature/mui typography variant 커스텀 구현
  src/constants/muiTheme.ts
Labels: Feature

#360 Feature/버튼 material tailwind 모듈 mui로 변경 #358
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
Labels: Design, P1, gpt review

#362 Feature/outlined button 아이콘 추가 기능 #359
  src/components/Button/OutlinedButton.tsx
Labels: Feature, gpt review

#380 Feature/회원가입 1단계 기능 구현 #295
  src/components/Input/BackgroundInput.tsx
  src/pages/SignUp/Section/SignUpFirstInputSection.tsx
  src/pages/SignUp/SignUp.recoil.ts
  src/pages/SignUp/SignUp.tsx
Labels: Feature, P1, gpt review

#315 Feature/도서추가삭제 모달창 UI 구성 #220
  src/api/dto.ts
  src/mocks/LibraryManageApi.ts
  src/pages/admin/LibraryManage/LibraryManage.tsx
  src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
  src/pages/admin/LibraryManage/Modal/DeleteBookModal.tsx
  src/pages/admin/LibraryManage/Selector/TotalBookNumberSelector.tsx
Labels: Feature, Design, P1

#392 Featrue/기본 폰트 크기 16 - 14px로 변경
  src/constants/muiTheme.ts
  tailwind.config.js
Labels: Design

#395 Feature/버튼 공통 컴포넌트 font size 커스텀 기능 추가 #391
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
Labels: Feature, Design

#398 Feature/버튼 line heigth 제거
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
Labels: Design

#384 Feature/subOrange 커스텀 색상 추가
  tailwind.config.js
Labels: Feature

#317 Feature/세미나 출석 세미나 input 기능 구현 #309
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Input/SeminarInput.tsx
Labels: Feature, P2

#330 Feature/세미나 출석 회원 출석상태 표시 #310
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/SeminarAttend.interface.ts
  src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
Labels: Feature, P3

#386 Feature/회원가입 API 틀 생성 #385
  src/api/dto.ts
  src/api/signUpApi.ts
Labels: Feature, P1, gpt review

#405 Feature/헤더 로그인 전 로그인 버튼 띄워주기 #269
  src/components/Layout/Header/Header.tsx
Labels: Feature, P3

#407 Feature/사이드바 라우터 연결 #271
  src/components/Navigation/SubCategoryNav.tsx
  src/constants/category.ts
Labels: Feature, P1

#409 Feature/사이드바 현재 페이지 하이라이팅 #272
  src/components/Navigation/CategoryNav.tsx
  src/components/Navigation/SubCategoryNav.tsx
Labels: Feature, P2

#348 Feature/세미나 출석 카드 3개 UI #331
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Feature, Design, P1, gpt review

#404 Feature/게임페이지 UI 구현 #401
  src/pages/Game/Game.tsx
  src/router/useMainRouter.tsx
Labels: Feature, P1, gpt review

#370 Feature/image 첨부 공통 컴포넌트 구현 #356
  src/components/Uploader/ImageUploader.tsx
  src/mocks/UtilApi.ts
Labels: Feature, P4
