Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-07, with the labels that each got.

#350 Feature/세미나 출석 카드 디자인 수정 #349
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Card/SeminarCard.tsx
  src/pages/senimarAttend/Input/SeminarInput.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Feature, Design, P1

#418 Feature/코드 옳을 시에만 출석상태 뜨도록 함
  src/pages/senimarAttend/Card/MemberCardContent.tsx
Labels: Feature

#422 Feature/게임 설명 모달 구현 #402
  src/pages/Game/Game.tsx
Labels: Feature, P3

#399 Feature/버튼 disable시 border색 변경 #397
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
Labels: Design, P1

#367 Feature/메인페이지 정기활동 #121
  src/api/dto.ts
  src/pages/home/Activity.tsx
  src/pages/home/Home.tsx
Labels: Feature, P1

#426 Feature/사이드바 디자인 적용 #273
  src/components/Navigation/SubCategoryNav.tsx
  src/constants/keeperTheme.ts
  tailwind.config.js
Labels: Design, P1

#435 Feature/인증 메일 모달 버튼 클릭 이벤트 핸들러 props로 받아오기 #434
  src/components/Modal/MailAuthenticationModal.tsx
Labels: Feature, P1

#440 Feature/로그인기능_#147
  package-lock.json
  package.json
  src/api/logInApi.ts
  src/pages/login/Login.tsx
  tsconfig.paths.json
Labels: P1

#452 Feature/matarial tailwind 사용된 부분 다 MUI로 변경 #451
  package-lock.json
  package.json
  src/components/Card/PostingCard.tsx
  src/components/Typography/PageTitle.tsx
  src/components/Uploader/ImageUploader.tsx
  src/constants/materialTailwindTheme.ts
  src/index.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/share/StudyInput.tsx
  src/pages/Study/share/StudyTextarea.tsx
  src/pages/home/Intro.tsx
  tailwind.config.js
Labels: Other, Design, P1

#453 Feature/react 17 버전으로 다운그레이드 #450
  package-lock.json
  package.json
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
  src/index.tsx
  src/pages/SignUp/Section/SignUpFirstInputSection.tsx
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/senimarAttend/Selector/SeminarSelector.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
  tsconfig.json
Labels: Other, P1

#457 Git action test
  src/api/logInApi.ts
  src/api/signUpApi.ts
  src/assets/logo/logo_default.svg
  src/assets/logo/logo_neon.svg
  src/components/Input/BackgroundInput.tsx
  src/components/Input/SearchInput.tsx
  src/components/Input/StandardInput.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Section/SearchSection.tsx
  src/components/Tab/StandardTab.tsx
  src/components/Table/StandardTable.tsx
  src/components/Uploader/ImageUploader.tsx
  src/constants/category.ts
  src/pages/Game/Game.tsx
  src/pages/SignUp/Section/SignUpFirstInputSection.tsx
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/login/Login.tsx
  src/pages/senimarAttend/Countdown/Countdown.tsx
  src/pages/senimarAttend/Input/SeminarInput.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Style

#455 Feature/게시글 작성 UI #429
  package-lock.json
  package.json
  src/components/Editor/StandardEditor.tsx
  src/components/Uploader/FileUploader.tsx
  src/pages/BoardWrite/BoardWrite.tsx
  src/pages/BoardWrite/Modal/SettingUploadModal.tsx
  src/router/useMainRouter.tsx
Labels: Feature, Design, P1

#441 Feature/게시글 조회 댓글 UI #437
  src/api/dto.ts
  src/components/Badge/CustomBadge.tsx
  src/mocks/commentApi.ts
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Card/CommentCard.tsx
  src/pages/board/BoardView/Card/CommentCardFooter.tsx
  src/pages/board/BoardView/Card/CommentCardHeader.tsx
  src/pages/board/BoardView/Card/CommentWriteCardAction.tsx
  src/pages/board/BoardView/Card/ReplyCard.tsx
  src/pages/board/BoardView/Section/CommentSection.tsx
  src/router/useMainRouter.tsx
Labels: Feature, Design, P4

#419 Feature/헬퍼텍스트+출석상태 css 수정 #417
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
Labels: Feature, P1

#460 Feature/게시글 작성 기능 구현 #430
  src/components/Uploader/FileUploadList.tsx
  src/components/Uploader/FileUploader.tsx
  src/pages/BoardWrite/BoardWrite.tsx
  src/utils/converter.ts
Labels: Feature, P1

#463 Feature/공통input component커스텀수정 #425
  src/components/Input/BackgroundInput.tsx
Labels: Feature, P1, gpt review

#443 Feature/도서검색 UI 구현 #369
  src/pages/Library/Card/BookCard.tsx
  src/pages/Library/Library.tsx
  src/router/useMainRouter.tsx
Labels: Design, P1

#444 Feature/게시글 조회 다른 게시글로 이동 UI #438
  src/api/dto.ts
  src/mocks/postApi.ts
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx
  src/pages/board/BoardView/Section/CommentSection.tsx
Labels: Feature, Design, P1

#470 Feature/게시글 설정 및 업로드 모달 기능 #469
  src/api/dto.ts
  src/pages/BoardWrite/BoardWrite.tsx
  src/pages/BoardWrite/Modal/SettingUploadModal.tsx
Labels: Feature, P1

#475 Feature/도서 신청 버튼 클릭시 모달창 생성 #446
  src/pages/Library/Card/BookCard.tsx
  src/pages/Library/Modal/RequestBookModal.tsx
Labels: Design, P1

#476 Feature/대출가능여부에 따른 텍스트 및 tooltip 구현 #458
  src/pages/Library/Library.tsx
  src/pages/Library/Status/BorrowStatus.tsx
Labels: Design

#478 Feature/게시글 조회 게시글 내용 UI #439
  src/api/dto.ts
  src/components/Viewer/StandardViewer.tsx
  src/mocks/postApi.ts
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Section/BannerSection.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
Labels: Feature, Design, P1
