Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-04, with the labels that each got.

#277 Feature/사이드바 제작 #201
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Sidebar/Sidebar.tsx
  src/components/Navigation/CategoryNav.tsx
  src/components/Navigation/SubCategoryNav.tsx
  src/constants/category.ts
  src/constants/keeperTheme.ts
Labels: Feature, P1

#328 Feature/테이블 체크박스 UI #299
  src/components/Table/StandardTable.interface.ts
  src/components/Table/StandardTable.tsx
Labels: Feature, P2

#336 ActionModal 모달 제목에 아이콘 추가 가능하도록 확장 #335
  src/components/Modal/ActionModal.tsx
Labels: Feature, P1

#337 Feature/주의 모달 공통 컴포넌트 #334
  src/components/Modal/WarningModal.tsx
Labels: Feature, P2

#332 Feature/모달창 색 변경 #327
  src/components/Modal/ActionModal.tsx
Labels: Design, P3

#326 Feature/label없을시 margin 제거
  src/components/Selector/Selector.tsx
Labels: Design

#340 Feature/공통 배경 인풋 구현 #339
  src/components/Input/BackgroundInput.tsx
Labels: Feature, P1

#338 Feature/회원가입 인풋 호출부 구현 #293
  src/pages/SignUp/SignUp.tsx
Labels: Feature, Design, P1
