Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-01, with the labels that each got.

#112 Feature/라우터 설정하기 #109
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/admin/SeminarManage.tsx
  src/pages/home/Home.tsx
  src/router/useMainRouter.tsx
Labels: Feature

#125 Feature/절대경로 설정하기 #114
  .eslintrc.js
  craco.config.ts
  package-lock.json
  package.json
  src/App.tsx
  src/router/useMainRouter.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: Feature, Refactor

#159 Feature/tailwind 관련 설정 #158
  package-lock.json
  package.json
  postcss.config.js
  src/index.tsx
  src/tailwind.css
  tailwind.config.js
Labels: Feature

#163 Feature/tailwindcss plugin 추가 #162
  .eslintrc.js
  package-lock.json
  package.json
  prettier.config.js
Labels: Feature

#170 Feature/tailwindcss 기본 폰트 지정 #168
  src/tailwind.css
Labels: Feature, Design
