Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-10, with the labels that each got.

#751 feat : 도서검색 글자수 over 처리
  src/pages/Library/Card/BookCard.tsx
Labels: Design

#767 feat : 스터디 삭제 기능 추가
  src/api/studyApi.ts
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Modal/StudyDeleteModal.tsx
Labels: Feature

#763 Feature/이메일 전송중과 완료 시 아이콘 띄우기 #629
  src/components/Input/EmailAuthInput.tsx
  src/pages/Profile/Modal/EditAccountModal.tsx
  src/pages/SignUp/Section/SignUpThirdInputSection.tsx
  src/pages/login/Search/SearchID.tsx
  src/pages/login/Search/SearchPWFirstStep.tsx
Labels: Feature, Design, P1

#771 Feature/에러 페이지 처리 #666
  src/assets/notFound/404.svg
  src/components/Layout/Container/FitContainer.tsx
  src/components/Layout/Container/FullContainer.tsx
  src/components/Layout/MainLayout.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/NotFound/SvgComponent/Svg404Component.tsx
  src/pages/Profile/Profile.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/board/BoardList/BoardList.tsx
  src/pages/board/BoardView/BoardView.tsx
  src/pages/login/Login.tsx
  src/pages/login/SearchAccount.tsx
  src/router/useMainRouter.tsx
  src/tailwind.css
  tailwind.config.js
Labels: Feature, Design, P1

#775 Feature/비밀번호 찾기 인증 코드 관련 처리
  src/api/SearchAccountApi.ts
  src/pages/login/Search/SearchPWFirstStep.tsx
  src/pages/login/Search/SearchPWSecondStep.tsx
Labels: Bug, Feature, P1

#766 Feature/스터디 반응형 #758
  src/api/dutyManageApi.ts
  src/api/logInApi.ts
  src/api/studyApi.ts
  src/components/Chip/MemberChip.tsx
  src/components/Input/AutoComplete.tsx
  src/components/Input/StandardInput.tsx
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Accordion/StudyAccordionBody.tsx
  src/pages/Study/Accordion/StudyAccordionHeader.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/share/StudyChip.tsx
  src/utils/converter.ts
Labels: Feature, Design

#776 Feature/첨부 파일 관련 반응형 처리
  src/components/Uploader/FileUploadList.tsx
  src/components/Viewer/FileViewer.tsx
Labels: Feature, Design

#777 Feature/도서관리 반응형 #772
  src/components/Table/StandardTable.tsx
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
  src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
  src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
Labels: Design, P1

#779 Feature/상벌점페이지 정렬 필터링 #686
  src/api/dto.ts
  src/api/meritApi.ts
  src/pages/admin/MeritManage/MeritManage.tsx
  src/pages/admin/MeritManage/Modal/DeleteMeritLogModal.tsx
  src/pages/admin/MeritManage/Modal/MemberMeritModal.tsx
  src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
  src/pages/admin/MeritManage/Tab/MeritLogTab.tsx
  src/pages/admin/MeritManage/Tab/MeritTypeTab.tsx
  src/pages/admin/MeritManage/Tab/UserMeritTab.tsx
Labels: Feature

#770 Feature/세미나 출석 상태 변경 기능 추가 #744
  src/api/dto.ts
  src/api/seminarApi.ts
  src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
  src/pages/admin/SeminarManage/Selector/StatusTypeSelector.tsx
  src/pages/admin/SeminarManage/SeminarManage.tsx
Labels: Feature

#782 Feature/메인페이지 반응형 처리 #684
  src/pages/home/Activity.tsx
  src/pages/home/Excellence.tsx
  src/pages/home/History.tsx
  src/pages/home/Home.tsx
  src/pages/home/Intro.tsx
  src/pages/home/Trendings.tsx
Labels: Feature, Design, P1

#784 feat : 도서관리 탭별 url 추가
  src/pages/admin/LibraryManage/LibraryManage.tsx
  src/router/useMainRouter.tsx
Labels: Feature

#749 Feature/활동인원 관리 변경확인 모달창 구현 #747
  src/api/memberApi.ts
  src/pages/admin/ActiveMemberManage/ActiveMemberManage.tsx
  src/pages/admin/ActiveMemberManage/Button/ChangeMemberTypeButton.tsx
  src/pages/admin/ActiveMemberManage/Button/MemberTypeChangeButton.tsx
  src/pages/admin/ActiveMemberManage/Input/MemberTypeChangeInput.tsx
  src/pages/admin/ActiveMemberManage/Modal/MemberTypeChangeModal.tsx
  src/pages/admin/ActiveMemberManage/Section/MemberTypeSection.tsx
  src/pages/admin/ActiveMemberManage/memberTypes.ts
Labels: Feature, P1

#781 Feature/랭킹페이지 수정 #780
  src/api/dto.ts
  src/pages/rank/Rank.tsx
  src/pages/rank/TopCard.tsx
Labels: Feature

#787 Feature/세미나 관리 테이블 관련 처리 #786
  src/components/Table/StandardTable.interface.ts
  src/components/Table/StandardTable.tsx
  src/pages/admin/SeminarManage/SeminarManage.tsx
Labels: Feature, P1

#788 fix : 로그인 실패 알림
  src/pages/login/Login.tsx
Labels: Bug

#783 Feature/활동인원 관리 반응형 #769
  src/pages/admin/ActiveMemberManage/ActiveMemberManage.tsx
  src/pages/admin/ActiveMemberManage/Button/MemberTypeChangeButton.tsx
  src/pages/admin/ActiveMemberManage/Section/MemberTypeSection.tsx
Labels: Design, P2

#790 Feature/게시글 조회 페이지 버그 픽스 #789
  src/api/postApi.ts
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Card/CommentCard.tsx
  src/pages/board/BoardView/Card/CommentCardFooter.tsx
  src/pages/board/BoardView/Modal/WarningDeductPointModal.tsx
  src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx
  src/pages/board/BoardView/Section/CommentSection.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
Labels: Bug, P1

#795 Feature/세미나 출석 페이지 버그 픽스 #792
  src/api/seminarApi.ts
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Bug, P1

#794 Feature/남프로필 처리
  src/pages/Profile/Modal/SendPointModal.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Profile/Section/ProfileSection.tsx
  src/pages/Profile/Tab/AttendanceTab/Section/AttendanceInfoSection.tsx
  src/pages/Profile/Tab/BoardTab/BoardTab.tsx
  src/pages/Profile/Tab/BoardTab/MyBoardTab.tsx
  src/pages/Profile/Tab/BoardTab/Table/MemberBoardTable.tsx
Labels: Feature, Design, P2

#799 Feature/게시글 조회 페이지 버그 픽스 #789
  src/api/postApi.ts
  src/components/Modal/ActionModal.tsx
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Modal/SecretPostModal.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
Labels: Bug, P1

#803 Feature/세미나 출석 페이지 버그 픽스 #792
  src/api/dto.ts
  src/api/seminarApi.ts
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Countdown/Countdown.tsx
Labels: Bug

#805 Feature/avartar 서버 프로필 공통 컴포넌트 #800
  src/api/dto.ts
  src/components/Avatar/ServerAvatar.tsx
  src/components/Card/PostingCard.tsx
  src/constants/muiTheme.ts
  src/pages/Profile/Section/FollowList.tsx
  src/pages/Profile/Section/ProfileSection.tsx
  src/pages/admin/ActiveMemberManage/Card/MemberCard.tsx
  src/pages/board/BoardView/Card/CommentCardFooter.tsx
  src/pages/board/BoardView/Card/CommentCardHeader.tsx
  src/pages/board/BoardView/Section/BannerSection.tsx
  src/pages/home/Trendings.tsx
  src/pages/rank/Rank.tsx
  src/pages/rank/TopCard.tsx
Labels: Feature, P1

#796 Feature/세미나관리 페이지 버그픽스 #791
  src/api/seminarApi.ts
  src/components/DatePicker/StandardDatePicker.tsx
  src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
  src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
  src/pages/admin/SeminarManage/Selector/StatusTypeSelector.tsx
Labels: Bug, P1

#809 fix : 세미나 관리 페이지 이동안되는 버그 해결
  src/api/seminarApi.ts
  src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
Labels: Bug

#807 Feature/스터디 버그 픽스 #806
  src/pages/Study/Modal/StudyModal.tsx
Labels: Bug

#797 Feature/프로필 페이지 버그 픽스 #793
  src/api/memberApi.ts
  src/components/Layout/Header/Menu/AccountMenu.tsx
  src/constants/badge.ts
  src/pages/Profile/Modal/EditAccountModal.tsx
  src/pages/Profile/Modal/EditProfileModal.tsx
  src/pages/Profile/Profile.tsx
Labels: Bug

#802 fix : 직책관리 페이지 버그 픽스
  src/mocks/DutyManageApi.ts
  src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
  src/pages/admin/DutyManage/DutyManage.tsx
  src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
  src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
Labels: Bug, P3

#810 fix : 직책관리 페이지 버그 픽스 코드 리뷰 반영
  src/mocks/DutyManageApi.ts
  src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
Labels: Bug, P2

#811 Feature/상벌점 페이지 버그픽스
  src/api/meritApi.ts
  src/components/Input/RadioButton.tsx
  src/components/Selector/Selector.tsx
  src/pages/admin/MeritManage/Modal/AddMeritModal.tsx
  src/pages/admin/MeritManage/Modal/MemberMeritModal.tsx
  src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
  src/pages/admin/MeritManage/Tab/MeritLogTab.tsx
  src/pages/admin/MeritManage/Tab/UserMeritTab.tsx
Labels: Bug

#814 Feature/메인페이지 반응형 QA
  src/pages/home/Activity.tsx
  src/pages/home/Home.tsx
Labels: Design

#813 Feature/이미지 업로더 기본 이미지로 수정 관련 처리 #591
  src/api/libraryManageApi.ts
  src/api/memberApi.ts
  src/api/postApi.ts
  src/components/Uploader/ImageUploader.tsx
  src/components/Uploader/ProfileImageUploader.tsx
  src/pages/Profile/Modal/EditProfileModal.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/admin/LibraryManage/Modal/UploadBookModal.tsx
  src/pages/board/BoardWrite/BoardWrite.tsx
  src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
Labels: Bug, Feature

#817 fix : 기수별 그룹화 및 비회원 색깔 추가
  src/pages/admin/ActiveMemberManage/Button/MemberTypeChangeButton.tsx
  src/pages/admin/ActiveMemberManage/Input/MemberTypeChangeInput.tsx
  src/pages/admin/ActiveMemberManage/memberTypes.ts
Labels: Design, P1

#815 Feature/도서관리 버그 픽스 #801
  src/api/libraryManageApi.ts
  src/pages/admin/LibraryManage/Modal/DeleteBookModal.tsx
  src/pages/admin/LibraryManage/Modal/UploadBookModal.tsx
  src/pages/admin/LibraryManage/SearchSection/BorrowingStatusSearchSection.tsx
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
Labels: Bug, P1

#818 fix : 출석랭킹에러fix
  src/pages/rank/Rank.tsx
Labels: Bug

#820 fix : 출제자일때도 뱃지 안보이도록
  src/pages/Profile/Section/BadgeSection.tsx
Labels: Bug

#822 fix : 모바일에선 중간 카드를 맨처음에 보여주도록
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Design

#823 Feature/세미나 출석 페이지 버그 픽스 #792
  src/api/seminarApi.ts
  src/components/Typography/TextTimer.tsx
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Countdown/Countdown.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Bug

#826 Feature/프로필 페이지 버그 픽스 #824
  src/pages/Profile/Section/BadgeSection.tsx
  src/pages/Profile/Section/FollowList.tsx
  src/pages/Profile/Section/ProfileSection.tsx
  src/pages/Profile/Tab/BookTab/BookTab.tsx
  src/pages/Profile/Tab/BookTab/Card/BookCard.tsx
Labels: Bug, Design

#827 Feature/활동인원 관리 버그 픽스 #825
  src/pages/admin/ActiveMemberManage/Section/MemberTypeSection.tsx
Labels: Bug

#828 Feature/세미나 관리 테이블 관련 처리 #786
  src/api/dto.ts
  src/api/seminarApi.ts
  src/components/Table/StandardTable.interface.ts
  src/components/Table/StandardTable.tsx
  src/pages/admin/SeminarManage/SeminarManage.tsx
Labels: Feature

#829 fix : 게임설명변경
  src/pages/Game/Game.tsx
Labels: Bug

#830 fix : pagenation key 변경
  src/pages/Profile/Tab/BoardTab/Table/MemberBoardTable.tsx
Labels: Bug

#833 Feature/버그&불편사항 제보 링크 추가 #831
  src/components/Layout/Sidebar/Sidebar.tsx
Labels: Feature
