Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-02, with the labels that each got.

#169 Feature/tailwindcss_커스텀_컬러_설정_#168
  tailwind.config.js
Labels: Feature, Priority-High

#165 Feature/테이블 공통 컴포넌트 제작 #130
  package-lock.json
  package.json
  src/components/Table/StandardTable.tsx
Labels: Feature

#176 Feature/recoil 설치 및 세팅 #175
  package-lock.json
  package.json
  src/index.tsx
Labels: Feature, Priority-High

#180 Feature/tailwindcss 폰트 사이즈 커스텀 #168
  tailwind.config.js
Labels: Feature, Design, Priority-High

#185 Feature/커스텀 색상 추가 #168
  tailwind.config.js
Labels: Feature, Design, Priority-High

#187 Feature/레이아웃 구성 #102
  src/App.tsx
  src/components/Layout/Container/FitContainer.tsx
  src/components/Layout/Container/FullContainer.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/index.ts
  src/components/Layout/MainLayout.tsx
  src/components/Layout/Sidebar/Sidebar.tsx
  src/components/Layout/Sidebar/index.ts
  src/router/useMainRouter.tsx
  tailwind.config.js
Labels: Feature, Priority-High

#188 Feature/api 받아오는 기본 틀 생성 #177
  .gitignore
  package-lock.json
  package.json
  src/api/aboutApi.ts
  src/api/dto.ts
  src/index.tsx
  tsconfig.paths.json
Labels: Feature

#191 Feature/공통 테이블 다크모드 디자인 적용 #130
  src/components/Table/StandardTable.tsx
Labels: Design, Priority-High

#186 Feature/EsLint_설정_수정 #184
  .eslintrc.js
Labels: Feature, Priority-High

#164 Feature/공통컴포넌트 모달 제작 #131
  .github/pull_request_template.md
  .vscode/settings.json
  src/components/Modal/ActionModal.tsx
Labels: Feature

#204 Feature/mocks 절대경로 설정 #203
  tsconfig.paths.json
Labels: Feature, Priority-High

#199 Feature/테이블 키 누락 워닝 제거 #130
  src/components/Table/StandardTable.tsx
Labels: Priority-Low

#205 Feature/버튼 공통 컴포넌트 #200
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
Labels: Feature, Design, Priority-High

#212 Feature/date picker 설치 및 세팅 #211
  package-lock.json
  package.json
  src/index.tsx
Labels: Feature, Priority-High

#214 Feature/material tailwind input 커스텀 #174
  src/constants/materialTailwindTheme.ts
Labels: Design, Priority-High

#197 Feature/tailwind 커스텀 폰트 사이즈 단위 변경 #168
  tailwind.config.js
Labels: Other, Priority-High

#218 Feature/테이블 페이지네이션 추가 #130
  src/components/Pagination/TablePagination.tsx
  src/components/Pagination/pagination.css
  src/components/Table/StandardTable.tsx
  src/constants/materialTailwindTheme.ts
  src/constants/muiTheme.ts
  src/index.tsx
Labels: Feature

#229 Feature/테이블 페이지네이션 개선 #228
  src/components/Pagination/StandardTablePagination.tsx
  src/components/Table/StandardTable.tsx
Labels: Refactor, Priority-High

#232 Feature/assets 절대경로 지정, 로고파일 svg 추가
  src/assets/logo/logo_default.svg
  src/assets/logo/logo_neon.svg
  tsconfig.paths.json
Labels: Feature

#234 Feature/react icon 설치
  package-lock.json
  package.json
Labels: Feature, Priority-High

#230 Feature/버튼 tailwincss 유틸리티 정렬 #200
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
Labels: Priority-High, Style

#242 Feature/버튼 상위 태그에 따라 높이 변경되지 않도록 처리 #241
  src/components/Button/FilledButton.tsx
  src/components/Button/OutlinedButton.tsx
  src/components/Button/TextButton.tsx
Labels: Feature, Priority-High

#244 Feature/기본 텍스트 컬러 흰색 지정 #243
  src/tailwind.css
Labels: Feature, Priority-High

#246 Feature/luxon 타입 정의된 라이브러리 설치 #245
  package-lock.json
  package.json
Labels: Feature, Priority-High

#248 Feature/mui 커스텀 컬러 설정 #247
  src/components/Pagination/StandardTablePagination.tsx
  src/constants/muiTheme.ts
Labels: Design, Priority-High

#235 Feature/테이블 데이터 셀 가공 가능하도록 처리 #130
  src/components/Table/StandardTable.interface.ts
  src/components/Table/StandardTable.tsx
Labels: Feature, Priority-High

#219 Feature/모달 열림 여부 props로 전달하도록 확장 #217
  src/components/Modal/ActionModal.tsx
Labels: Feature, Priority-High

#173 Feature/세미나관리 페이지 UI
  src/mocks/SeminarManageApi.ts
  src/pages/admin/SeminarManage.tsx
Labels: Feature, Priority-Low
