Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-03, with the labels that each got.

#239 Feature/datepicker 공통컴포넌트 제작 #213
  src/components/DatePicker/StandardDatePicker.tsx
Labels: Feature, Priority-High

#268 Feature/헤더 구성 #103
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/Menu/AccountMenu.tsx
Labels: Feature, Priority-High

#276 Feature/FullContainer 넓이 full로 잡기
  src/components/Layout/Container/FullContainer.tsx
Labels: Feature, Priority-High

#215 Feature/도서관리 페이지 UI #145
  src/api/dto.ts
  src/mocks/LibraryManageApi.ts
  src/pages/admin/LibraryManage/LibraryManage.tsx
  src/router/useMainRouter.tsx
Labels: Feature, Design, Priority-High

#224 Feature/세미나 출석 회원 UI #207
  src/pages/senimarAttend/DoAttend.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
  src/pages/senimarAttend/SetSeminar.tsx
  src/router/useMainRouter.tsx
Labels: Feature, Design, Priority-High

#259 Feature/메인페이지 메인 #116
  public/img/background_galaxy.png
  src/pages/home/Home.tsx
  src/pages/home/Intro.tsx
  tailwind.config.js
Labels: Feature, Priority-High

#281 Feature/테이블과 페이지네이션 사이 간격 고정 #280
  src/components/Table/StandardTable.tsx
Labels: Refactor, Priority-High

#265 Feature/공통 액션 모달 디자인 리팩토링 #263
  src/components/Modal/ActionModal.tsx
Labels: Design, Priority-Low

#264 Feature/셀렉터_공통_컴포넌트_#238
  src/components/Selector/Selector.tsx
Labels: Feature, Priority-High

#171 Feature/스터디 페이지 UI 구성 #153
  src/mocks/StudyApi.ts
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/OldStudy.tsx
  src/pages/Study/Study.tsx
  src/pages/Study/share/StudyChip.tsx
  src/pages/Study/share/StudyInput.tsx
  src/pages/Study/share/StudySelect.tsx
  src/pages/Study/share/StudyTextarea.tsx
  src/router/useMainRouter.tsx
Labels: Feature, Design, Priority-High

#285 fix: fillButton import 안한거 수정
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Bug, Priority-High

#249 Feature/검색 인풋 공통컴포넌트 구현 #240
  src/components/Input/SearchInput.tsx
Labels: Feature, Priority-High

#282 Feature/인풋 공통 컴포넌트 #279
  src/components/Input/StandardInput.tsx
Labels: Feature, Priority-High

#267 Feature/테이블 그리드뷰 #130
  src/components/Card/PostingCard.interface.ts
  src/components/Card/PostingCard.tsx
  src/components/Table/GridTable.tsx
Labels: Feature

#289 Feature/ActionModal MUI 컴포넌트 사용으로 변경 #287
  src/components/Modal/ActionModal.tsx
  src/pages/Study/Modal/StudyModal.tsx
Labels: Feature, Refactor, P1

#284 Feature/세미나 출석 카드 컴포넌트 분리 #283
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Card/SeminarCard.tsx
  src/pages/senimarAttend/Countdown/Countdown.tsx
  src/pages/senimarAttend/DoAttend.tsx
  src/pages/senimarAttend/Input/SeminarInput.tsx
  src/pages/senimarAttend/Selector/SeminarSelector.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
  src/pages/senimarAttend/SetSeminar.tsx
Labels: Feature, P1

#301 Feature/인풋공통컴포넌트 border색 포인트컬러로 변경
  src/components/Input/StandardInput.tsx
Labels: Design

#305 Feature/MUI 폰트 적용
  src/constants/muiTheme.ts
Labels: Design, P4

#303 Feature/라우터에 회원가입 페이지 추가 #302
  src/pages/SignUp/SignUp.tsx
  src/router/useMainRouter.tsx
Labels: Feature, P1
