Repository KEEPER31337/Homepage-Front-R2, pull requests merged in 2023-08, with the labels that each got.

#485 Feature/사이드바 권한 관련 처리 #278
  package-lock.json
  package.json
  src/api/dto.ts
  src/components/Layout/Sidebar/Sidebar.tsx
  src/components/Navigation/CategoryNav.tsx
  src/components/Navigation/SubCategoryNav.tsx
  src/constants/category.ts
  src/hooks/useCheckAuth.ts
  src/pages/login/Login.tsx
  src/recoil/member.recoil.ts
  src/router/useMainRouter.tsx
  tsconfig.paths.json
Labels: Feature, P1

#491 Feature/게시글 작성 api 연동 #431
  src/api/dto.ts
  src/api/postApi.ts
  src/pages/BoardWrite/BoardWrite.tsx
  src/pages/BoardWrite/Modal/SettingUploadModal.tsx
  src/pages/board/BoardList.tsx
Labels: Feature, P1

#483 Feature/야구게임 규칙 #482
  src/pages/Game/Game.tsx
Labels: Feature

#480 Feature/직책관리 페이지 UI 구성 #447
  src/assets/dutyManage/badge_1_chairman.gif
  src/assets/dutyManage/badge_2_vice_chairman.gif
  src/assets/dutyManage/badge_3_external_manager.gif
  src/assets/dutyManage/badge_4_study_manager.gif
  src/assets/dutyManage/badge_5_it_manager.gif
  src/assets/dutyManage/badge_6_clerk.gif
  src/assets/dutyManage/badge_7_administrator.gif
  src/assets/dutyManage/badge_8_librarian.gif
  src/mocks/DutyManageApi.ts
  src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
  src/pages/admin/DutyManage/DutyManage.tsx
  src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
  src/pages/admin/DutyManage/Tooltip/DescriptionRoleDutyTooltip.tsx
  src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
  src/router/useMainRouter.tsx
Labels: Feature, P1

#497 feat : 추가, 삭제, 수정 버튼 제작
  src/components/Button/ActionButton.tsx
Labels: Feature, P1

#495 Feature/게시글 조회 api 연동 #492
  src/api/commentApi.ts
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Image/ServerImg.tsx
  src/mocks/postApi.ts
  src/pages/BoardWrite/BoardWrite.tsx
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Card/CommentCard.tsx
  src/pages/board/BoardView/Card/CommentCardFooter.tsx
  src/pages/board/BoardView/Card/CommentCardHeader.tsx
  src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx
  src/pages/board/BoardView/Section/BannerSection.tsx
  src/pages/board/BoardView/Section/CommentSection.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
Labels: Feature, P1

#501 Feature/StandardTablePagination 외부 props 받아와 제어 #499
  src/components/Pagination/StandardTablePagination.interface.ts
  src/components/Pagination/StandardTablePagination.tsx
  src/components/Table/StandardTable.tsx
  src/hooks/useGetPage.ts
Labels: Feature, P1

#498 Feature/게시판 테이블 목록 조회 기능 #135
  package.json
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Table/StandardTable.tsx
  src/components/Viewer/StandardViewer.tsx
  src/pages/board/BoardList.tsx
  src/pages/board/BoardView/BoardView.tsx
  src/router/useMainRouter.tsx
  src/utils/converter.ts
Labels: Feature, P1

#484 Feature/도서 목록 조회 api 연결 #464
  src/api/dto.ts
  src/api/libraryApi.ts
  src/pages/Library/Card/BookCard.tsx
  src/pages/Library/Library.tsx
  src/pages/Library/Modal/RequestBookModal.tsx
  src/pages/Library/Status/BorrowStatus.tsx
Labels: Feature, P1

#505 Refactor/게시글 생성 페이지 폴더 위치 변경
  src/pages/board/BoardWrite/BoardWrite.tsx
  src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
  src/router/useMainRouter.tsx
Labels: Refactor, P1

#508 Feature/게시글 조회 api 스펙 변경 반영 #503
  src/api/dto.ts
  src/api/postApi.ts
  src/mocks/postApi.ts
  src/pages/board/BoardView/Section/PostSection.tsx
Labels: P1

#490 Feature/랭킹페이지 UI 구성 #329
  public/img/sampleProfile.svg
  src/mocks/AttendRankApi.ts
  src/mocks/PointRankApi.ts
  src/pages/rank/Rank.tsx
  src/pages/rank/TopCard.tsx
  src/router/useMainRouter.tsx
Labels: Feature, P1

#519 Feature/게시판 페이지네이션 적용 #518
  src/api/dto.ts
  src/api/postApi.ts
  src/hooks/useGetPage.ts
  src/hooks/usePagination.ts
  src/pages/board/BoardList.tsx
Labels: P1

#520 Feature/세미나_삭제_모달_UI_#138
  src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
  src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
  src/pages/admin/SeminarManage/SeminarManage.tsx
Labels: Feature, P1

#513 Feature/도서 대출 신청 api 연결 #487
  src/api/libraryApi.ts
  src/pages/Library/Library.tsx
  src/pages/Library/Modal/RequestBookModal.tsx
Labels: Feature, P1

#514 Feature/게시글 작성 세부 기능 구현 #430
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Editor/StandardEditor.tsx
  src/components/Input/StandardInput.tsx
  src/components/Modal/ActionModal.tsx
  src/components/Uploader/FileUploader.tsx
  src/components/Uploader/ImageUploader.tsx
  src/constants/errorMsg.ts
  src/pages/board/BoardList.tsx
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
  src/pages/board/BoardWrite/BoardWrite.tsx
  src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
  src/router/useMainRouter.tsx
Labels: Feature, P1

#515 Feature/페이지네이션 기능 추가 #510
  src/api/libraryApi.ts
  src/pages/Library/Library.tsx
Labels: Feature

#537 Feature/홈페이지 구성 관련 처리 #536
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/index.html
  public/manifest.json
  src/components/Layout/Container/FitContainer.tsx
Labels: Feature

#521 Feature/게시판 리스트 그리드 뷰 전환 기능 #134
  src/api/dto.ts
  src/components/Button/TableViewSwitchButton.tsx
  src/components/Card/PostingCard.interface.ts
  src/components/Card/PostingCard.tsx
  src/components/Image/ServerImg.tsx
  src/components/Table/GridTable.tsx
  src/pages/board/BoardList.tsx
  src/recoil/view.recoil.ts
  src/utils/converter.ts
Labels: Feature, P1

#523 Feature/실행 스크립트에 cross-env 추가 #522
  package-lock.json
  package.json
Labels: Bug, Feature, P1

#525 Feature/에러_공통_처리_훅_제작_#524
  src/hooks/useGetApiError.ts
  src/index.tsx
Labels: Feature, P1

#533 Feature/로그인 시 계정 정보 저장 및 헤더 반영 #530
  src/api/authApi.ts
  src/api/dto.ts
  src/api/logInApi.ts
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/Menu/AccountMenu.tsx
  src/hooks/useCheckAuth.ts
  src/pages/login/Login.tsx
  src/recoil/member.recoil.ts
Labels: P1

#545 Feature/게임 불러오기
  package-lock.json
  package.json
  src/pages/Game/Baseball/Baseball.tsx
  src/pages/Game/Baseball/api/baseballApi.ts
  src/pages/Game/Baseball/api/baseballDto.ts
  src/pages/Game/Baseball/components/CountdownBar.tsx
  src/pages/Game/Baseball/components/InfoModal.tsx
  src/pages/Game/Baseball/components/NoticeEnd.tsx
  src/pages/Game/Baseball/components/NumberInput.tsx
  src/pages/Game/Baseball/components/PointInfo.tsx
  src/pages/Game/Baseball/components/TurnInfoBoard.tsx
  src/pages/Game/Baseball/components/TurnInfoCard.tsx
  src/pages/Game/Baseball/screens/GamePlay.tsx
  src/pages/Game/Baseball/screens/GameStart.tsx
  src/pages/Game/Game.tsx
  src/tailwind.css
  tailwind.config.js
Labels: Feature

#527 Feature/도서 대여 목록 조회 api 연결 #486
  src/api/dto.ts
  src/api/libraryApi.ts
  src/pages/Library/Library.tsx
  src/pages/Library/Status/BorrowStatus.tsx
Labels: Feature, P1

#534 Feature/search section 기능 구현 #532
  src/components/Input/SearchInput.tsx
  src/components/Input/StandardInput.tsx
  src/components/Section/SearchSection.tsx
  src/components/Selector/Selector.tsx
  src/pages/Library/Library.tsx
  src/pages/admin/LibraryManage/LibraryManage.tsx
  src/pages/board/BoardList.tsx
Labels: Feature, P1

#538 Feature/게시글 조회 댓글 섹션 추가 api 적용 #494
  src/api/commentApi.ts
  src/api/dto.ts
  src/hooks/useCheckAuth.ts
  src/mocks/commentApi.ts
  src/pages/board/BoardView/Card/CommentCard.tsx
  src/pages/board/BoardView/Card/CommentCardFooter.tsx
  src/pages/board/BoardView/Card/CommentCardHeader.tsx
  src/pages/board/BoardView/Card/ReplyCard.tsx
  src/pages/board/BoardView/Menu/CommentMenu.tsx
  src/pages/board/BoardView/Section/CommentSection.tsx
Labels: Feature, P1

#542 Feature/autocomplete 공통컴포넌트 #432
  src/components/Input/AutoComplete.tsx
Labels: Feature, P1

#489 Feature/세미나 출석 세미나 시작, 출석 api 연동 #416
  package-lock.json
  package.json
  src/api/dto.ts
  src/api/seminarApi.ts
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Input/SeminarInput.tsx
  src/pages/senimarAttend/SeminarAttend.interface.ts
  src/pages/senimarAttend/SenimarAttend.tsx
  src/pages/senimarAttend/Status/SeminarAttendStatus.tsx
Labels: Feature, P1

#547 feat : 도서관리페이지 tab추가 및 tab 컴포넌트 작성
  src/pages/admin/LibraryManage/LibraryManage.tsx
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
  src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
  src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
Labels: Feature, P1

#560 Feature/게시판 검색 기능 구현 #133
  src/api/dto.ts
  src/components/Pagination/StandardTablePagination.tsx
  src/pages/board/BoardList/BoardList.tsx
  src/pages/board/BoardList/SearchSection/BoardSearchSection.tsx
Labels: Feature, P1

#549 Feature/도서관리 탭 search section 추가 #548
  src/pages/Library/Library.tsx
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
Labels: Design, P1

#546 Feature/401에러 로그인 페이지로 이동 #502
  src/App.tsx
  src/hooks/useGetApiError.ts
  src/index.tsx
Labels: Feature, P1

#557 Feature/책목록가져오기 api 연결 #550
  src/api/dto.ts
  src/api/libraryApi.ts
  src/api/libraryManageApi.ts
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
Labels: Feature, P1

#539 Feature/게시글 조회 세부 기능 추가 #526
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Editor/StandardEditor.tsx
  src/mocks/postApi.ts
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx
  src/pages/board/BoardView/Section/BannerSection.tsx
  src/pages/board/BoardView/Section/PostSection.tsx
  src/pages/board/BoardWrite/BoardWrite.tsx
Labels: Feature, P1

#564 Feature/도서추가 모달 기능 구현 #551
  src/api/dto.ts
  src/api/libraryManageApi.ts
  src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
Labels: Feature, P1

#577 Feature/게시판 남은 작업 처리
  src/api/postApi.ts
  src/components/Table/StandardTable.tsx
  src/pages/board/BoardList/BoardList.tsx
Labels: Feature, P1

#573 Feature/승인요청 탭 승인, 거부 기능 추가 #571
  src/api/libraryManageApi.ts
  src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
Labels: Feature, P2

#506 Feature/세미나 출석 이전,현재,최신 세미나 조회 #481
  src/api/seminarApi.ts
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
Labels: Feature, P1

#575 Feature/대출 현황 탭 연체도서 목록 받아오기 #574
  src/api/dto.ts
  src/api/libraryManageApi.ts
  src/pages/admin/LibraryManage/Modal/OverdueBookModal.tsx
  src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
  src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
Labels: Feature, P1

#580 Feature/게시판 남은 작업 처리
  package-lock.json
  package.json
  src/api/dto.ts
  src/api/postApi.ts
  src/components/Layout/MainLayout.tsx
  src/pages/board/BoardList/BoardList.tsx
  src/pages/board/BoardView/BoardView.tsx
  src/pages/board/BoardView/Modal/SecretPostModal.tsx
  src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
Labels: Feature, P1

#566 Feature/랭킹페이지 api 연결 #543
  src/api/dto.ts
  src/api/rankApi.ts
  src/mocks/AttendRankApi.ts
  src/mocks/PointRankApi.ts
  src/pages/rank/Rank.tsx
  src/pages/rank/TopCard.tsx
Labels: Feature, P1

#512 Feature/메인페이지 트렌딩 #117
  src/api/dto.ts
  src/api/postApi.ts
  src/pages/home/Home.tsx
  src/pages/home/Trendings.tsx
Labels: Feature, P1

#488 Feature/아이디,비밀번호 찾기 페이지_#351
  src/api/SearchAccountApi.ts
  src/api/logInApi.ts
  src/pages/login/Login.tsx
  src/pages/login/Search/SearchID.tsx
  src/pages/login/Search/SearchPW.tsx
  src/pages/login/Search/SearchPWFirstStep.tsx
  src/pages/login/Search/SearchPWSecondStep.tsx
  src/pages/login/Search/SearchPWThirdStep.tsx
  src/pages/login/SearchAccount.tsx
  src/router/useMainRouter.tsx
  src/utils/validateEmail.ts
Labels: Feature, P1

#582 Feature/스터디 모달 상세 구현 #155
  src/api/dto.ts
  src/api/studyApi.ts
  src/components/Input/StandardInput.tsx
  src/mocks/StudyApi.ts
  src/pages/Study/Accordion/StudyAccordion.tsx
  src/pages/Study/Modal/StudyModal.tsx
  src/pages/Study/OldStudy.tsx
  src/pages/Study/Study.interface.ts
  src/pages/Study/Study.tsx
  src/pages/Study/share/StudyTextarea.tsx
Labels: Feature, Design, P1

#563 Feature/출석체크페이지 권한에 따른 이동 #540
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/SenimarAttend.tsx
  src/recoil/seminarStarter.recoil.ts
Labels: Feature, P1

#565 Feature/출석 체크 페이지 input 라이브러리 적용 #541
  package-lock.json
  package.json
  src/pages/senimarAttend/Card/BossCardContent.tsx
  src/pages/senimarAttend/Card/MemberCardContent.tsx
  src/pages/senimarAttend/Input/SeminarInput.tsx
Labels: Feature

#569 Feature/직책관리 페이지 API 연결 #555
  src/api/dto.ts
  src/api/dutyManageApi.ts
  src/mocks/DutyManageApi.ts
  src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
  src/pages/admin/DutyManage/DutyManage.tsx
  src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
  src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
Labels: Feature, P1

#581 feat : 도서삭제 기능 추가
  src/api/dto.ts
  src/api/libraryManageApi.ts
  src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
  src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
Labels: Feature, P1
